---
#language: python
#python: "2.7"
sudo: required
dist: trusty

before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq

install:
  # Install Ansible.
  - pip install ansible

  # Add ansible.cfg to pick up roles path.
  #- "printf '[defaults]\nroles_path = ../' > ansible.cfg"

script:
  - ansible-playbook -i tests/inventory site.yml --syntax-check
  - ansible-playbook -i tests/inventory site.yml
