# Site settings
title: Machina, a ansible Modul
tag_text: Machina
description: Machina is a Jekyll theme that supports single-page websites only, but supports them well. Yes, it’s responsive.

# Build settings
markdown: kramdown

exclude: ["README.md"]
