# Site settings
title: Machina, an ansible playbook
tag_text: // machina
description: Machina is a ansible playbook to install the needed Software for RefugeesOnRails on a Ubuntu 14.04 Desktop
# Build settings
markdown: kramdown

exclude: ["README.md"]
