---
# tasks file for machina

- name: get the real username when not ssh
  command: id -un
  register: id_output
  when: ansible_user == null or ansible_user is undefined
  sudo: no

- name: set USER via id
  set_fact: local_user={{ id_output.stdout }}
  when: ansible_user == null or ansible_user is undefined

- name: set USER via ssh
  set_fact: local_user={{ ansible_ssh_user }}
  when: ansible_user != null and ansible_user is defined

- name: update apt cache
  apt: update_cache=yes

- name: install packages
  apt: name={{ item }} state=present
  with_items:
    - aptitude
    - build-essential
    - git
    - postgresql
    - redis-server
    - python-dev
    - python-setuptools
    - python-virtualenv
    - python-pycurl
    - nodejs
    - sqlite3
    - libsqlite3-dev
    # ruby dependency
    - libssl-dev
    - libreadline-dev
    - zlib1g-dev
    - libffi-dev # not sure?
    - libpq-dev # required for pg-gem

# Update all packages to the latest version
- name: Upgrade all Packages
  apt: upgrade=yes

- name: add heroku toolbelt key
  apt_key: data="{{ lookup('file', 'release.key') }}" state=present

- name: add heroku toolbelt repo
  apt_repository: repo="deb http://toolbelt.heroku.com/ubuntu ./" state=present update_cache=yes

- name: install heroku toolbelt
  apt: name=heroku-toolbelt state=present

- name: add google chrome key
  apt_key: url=https://dl-ssl.google.com/linux/linux_signing_key.pub state=present

# via https://github.com/cmprescott/ansible-role-chrome/blob/master/tasks/setup-apt.yml
- name: ensure previous repository for Google Chrome is absent, as Google removed the x86 distribution
  apt_repository: repo='deb http://dl.google.com/linux/chrome/deb/ stable main' state=absent

- name: ensure Google chrome repo present, using a workaround for missing x86 distribution
  copy:
    content: "deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main"
    dest: "/etc/apt/sources.list.d/google-chrome.list"
  register: google_repo

- name: update cache
  apt: update_cache=yes
  when: google_repo.changed

- name: prevent automagical adding of google repos
  file:
    path=/etc/default/google-chrome
    state=touch

- name: install google chrome
  apt: name=google-chrome-stable state=installed

- name: install pip
  easy_install: name=pip

- name: install awscli
  pip: name=awscli

- name: download atom editor
  get_url:
    url=https://github.com/atom/atom/releases/download/v1.7.2/atom-amd64.deb
    dest=~/atom-amd64.deb
    validate_certs=no #it's a error in ubuntu
    #checksum=sha256:20ae3a6ab509923e2b4ccd05d84079aa113be286a9052fecc35a31e833e77ce5
  sudo: false

- name: install atom editor
  apt: deb=/home/{{ local_user }}/atom-amd64.deb

- name: install rbenv
  git:
    repo=https://github.com/sstephenson/rbenv.git
    dest=~/.rbenv
  sudo: false

- name: install ruby-build for rbenv
  git:
    repo=https://github.com/sstephenson/ruby-build.git
    dest=~/.rbenv/plugins/ruby-build
  sudo: false

- name: set rbenv
  lineinfile:
    dest=~/.profile
    regexp='{{ item.regex }}'
    line='{{ item.line }}'
    state=present
    create=yes
  with_items:
    - {regex: '/.rbenv/bin:', line: 'export PATH="$HOME/.rbenv/bin:$PATH"'}
    - {regex: 'rbenv init -', line: 'eval "$(rbenv init -)"'}
  sudo: false

- name: install ruby 2.2.3 via rbenv
  shell: sudo -iu {{ local_user }} rbenv install 2.2.3
  args:
    creates: /home/{{ local_user }}/.rbenv/versions/2.2.3

- name: setting ruby 2.2.3 global
  shell: sudo -iu {{ local_user }} rbenv global 2.2.3

- name: install bundler and rails gems
  shell: sudo -iu {{ local_user }} gem install bundler rails

- name: install node via nvm
  shell: wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.30.2/install.sh | bash
  sudo: false
  args:
    creates: /home/{{ local_user }}/.nvm

- name: install version node v4
  shell: sudo -iu {{ local_user }} bash -lic "nvm install v4 && nvm alias default v4"
  args:
    creates: /home/{{ local_user }}/.nvm/alias/default
