---
# tasks file for machina
- name: update apt cache
  apt: update_cache=yes

- name: install packages
  apt: name={{ item }} state=present
  with_items:
    - build-essential
    - git
    - postgresql
    - redis-server
    - python-dev
    - python-setuptools
    - python-virtualenv

# Update all packages to the latest version
- name: Update all Packages
  apt: upgrade=yes

- name: add heroku toolbelt key
  apt_key: url=https://toolbelt.heroku.com/apt/release.key state=present

- name: add heroku toolbelt repo
  apt_repository: repo="deb http://toolbelt.heroku.com/ubuntu ./" state=present update_cache=yes

- name: install heroku toolbelt
  apt: name=heroku-toolbelt state=present

- name: install rbenv
  git:
    repo=https://github.com/sstephenson/rbenv.git
    dest=~/.rbenv
  sudo: false

- name: set rbenv
  lineinfile:
    dest=~/.bashrc
    regexp='{{ item.regex }}'
    line='{{ item.line }}'
    state=present
    create=yes
  with_items:
    - {regex: '/.rbenv/bin:', line: 'export PATH="$HOME/.rbenv/bin:$PATH"'}
    - {regex: 'rbenv init -', line: 'eval "$(rbenv init -)"'}
  sudo: false

- name: add google chrome key
  apt_key: url=https://dl-ssl.google.com/linux/linux_signing_key.pub state=present

- name: add google chrome repo
  apt_repository: repo="deb http://dl.google.com/linux/chrome/deb/ stable main" state=present update_cache=yes

- name: install google chrome
  apt: name=google-chrome-stable state=installed

- name: install pip
  easy_install: name=pip

- name: install awscli
  pip: name=awscli

- name: download atom editor
  get_url:
    url=https://github.com/atom/atom/releases/download/v1.1.0/atom-amd64.deb
    dest=~/atom-amd64.deb
    #checksum=sha256:20ae3a6ab509923e2b4ccd05d84079aa113be286a9052fecc35a31e833e77ce5
  sudo: false

- name: install atom editor
  apt: deb=/home/{{ ansible_ssh_user }}/atom-amd64.deb
